# Generated by Django 5.2.9 on 2026-03-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameIndex(
            model_name='pageview',
            new_name='analytics_p_path_dd882f_idx',
            old_name='analytics_p_path_idx',
        ),
    ]
