"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

Environment Variables:
  DEBUG          - "True" for development (default: "False")
  SECRET_KEY     - Required in production, auto-generated in dev
  ALLOWED_HOSTS  - Comma-separated hosts (default: "localhost,127.0.0.1")
  CORS_ORIGINS   - Comma-separated CORS origins (default: dev localhost)
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR / ".env")


# =============================================================================
# SECURITY SETTINGS (Environment-driven)
# =============================================================================

# DEBUG: Default to False (safe for production)
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")

# SECRET_KEY: Must be set in production
_secret_key_env = os.environ.get("SECRET_KEY")
if _secret_key_env:
    SECRET_KEY = _secret_key_env
elif DEBUG:
    # Development fallback - NEVER use in production
    SECRET_KEY = "django-insecure-dev-only-key-do-not-use-in-production"
else:
    raise ValueError(
        "SECRET_KEY environment variable is required in production mode. "
        "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )

# ALLOWED_HOSTS: From environment or safe defaults
_allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "")
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
else:
    # Development defaults
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
    if DEBUG:
        # Add local network IPs for mobile app testing in dev
        ALLOWED_HOSTS += ["192.168.0.162", "192.168.31.78"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party libraries
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt.token_blacklist",  # JWT token blacklisting
    "django_celery_beat",  # Stage 14: Periodic tasks
    "drf_spectacular",     # M002: OpenAPI 3.0 schema + Swagger UI
    "import_export",       # M003/S02: Bulk CSV/XLSX import via Django Admin
    "apps.webhooks",       # M003/S04: Outgoing webhooks

    # Our apps
    "apps.accounts",
    "apps.locations",
    "apps.jobs",
    "apps.maintenance",
    "apps.support",
    "apps.api",
    "apps.marketing",
    "apps.analytics",
    "apps.emails",
    "storages",  # S3-compatible file storage
]


AUTH_USER_MODEL = "apps_accounts.User"


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "apps" / "emails" / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# =============================================================================
# Database (Environment-driven)
# =============================================================================

# Support DATABASE_URL for production (postgres://user:pass@host:port/db)
_database_url = os.environ.get("DATABASE_URL")
if _database_url:
    import urllib.parse
    url = urllib.parse.urlparse(_database_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': url.path[1:],  # Remove leading slash
            'USER': url.username,
            'PASSWORD': url.password,
            'HOST': url.hostname,
            'PORT': url.port or '5432',
            'CONN_MAX_AGE': 600,  # Connection pooling
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }
else:
    # Development: SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Dubai"

USE_I18N = True
USE_TZ = True


# Static files

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media (uploads)
# Production: S3-compatible storage (set AWS_STORAGE_BUCKET_NAME env var)
# Development: local filesystem (default when no bucket configured)

_storage_bucket = os.getenv("AWS_STORAGE_BUCKET_NAME")

if _storage_bucket:
    # S3-compatible storage (AWS S3, DigitalOcean Spaces, Cloudflare R2)
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

    AWS_STORAGE_BUCKET_NAME = _storage_bucket
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "fra1")
    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")

    # For DigitalOcean Spaces / Cloudflare R2 — set custom endpoint
    AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL")  # e.g. https://fra1.digitaloceanspaces.com

    # Public read access for media files (photos, documents)
    AWS_DEFAULT_ACL = os.getenv("AWS_DEFAULT_ACL", "public-read")
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",  # 1 day cache
    }
    AWS_QUERYSTRING_AUTH = False  # Don't add auth querystring to URLs

    # Media URL from CDN or bucket
    MEDIA_URL = os.getenv(
        "MEDIA_URL",
        f"https://{_storage_bucket}.{AWS_S3_REGION_NAME}.digitaloceanspaces.com/"
    )
    MEDIA_ROOT = ""  # Not used with S3
else:
    # Local filesystem (development)
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# DRF

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "10/minute",
        # Auth endpoints — tighter limits to prevent brute force
        "auth_login": "5/minute",
        "auth_signup": "3/minute",
        "auth_password_reset": "3/minute",
        # M006/S04: Per-endpoint granular throttle scopes
        "check_in": "60/hour",
        "photo_upload": "120/hour",
        "webhook": "1000/day",
        "manager_dashboard": "300/hour",
        "api_key": "10000/day",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# =============================================================================
# drf-spectacular — OpenAPI 3.0 Schema (M002: API Docs)
# =============================================================================

SPECTACULAR_SETTINGS = {
    "TITLE": "Proof Platform API",
    "DESCRIPTION": (
        "REST API for the Proof Platform (CleanProof + MaintainProof).\n\n"
        "## Authentication\n\n"
        "Manager/owner endpoints use **JWT Bearer** tokens.\n"
        "Obtain tokens via `POST /api/manager/auth/login/`.\n\n"
        "Mobile cleaner endpoints use **Token** auth (`Authorization: Token <key>`).\n\n"
        "## Rate Limits\n\n"
        "Anonymous endpoints: 10 requests/minute."
    ),
    "VERSION": os.getenv("APP_VERSION", "1.0.0"),
    "SERVE_INCLUDE_SCHEMA": False,      # don't include /api/schema/ in itself
    "SERVE_PUBLIC": True,               # schema accessible without auth
    "COMPONENT_SPLIT_REQUEST": True,    # separate request/response schemas
    "SORT_OPERATIONS": True,
    # Security schemes
    "SECURITY": [{"jwtAuth": []}],
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "jwtAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": "JWT access token. Obtain via POST /api/manager/auth/login/",
            },
            "tokenAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "Authorization",
                "description": "Token auth for mobile cleaner app. Format: `Token <key>`",
            },
        }
    },
    # Tags for grouping endpoints in Swagger UI
    "TAGS": [
        {"name": "auth", "description": "JWT authentication — login, refresh, logout"},
        {"name": "billing", "description": "Paddle billing — subscription status and webhooks"},
        {"name": "maintenance", "description": "MaintainProof — service visits, assets, technicians"},
        {"name": "jobs", "description": "CleanProof — job management"},
        {"name": "company", "description": "Company and team management"},
        {"name": "reports", "description": "PDF and Excel report generation"},
        {"name": "health", "description": "Health check"},
    ],
}


# =============================================================================
# JWT Configuration (djangorestframework-simplejwt)
# =============================================================================

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=90),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",

    "TOKEN_OBTAIN_SERIALIZER": "apps.api.serializers_jwt.ProofTokenObtainPairSerializer",
}


# =============================================================================
# Paddle Billing Configuration (M001-sijc46: Launch-Ready Billing & Auth)
# All IDs from environment — no hardcoded Paddle identifiers (D005)
# =============================================================================
PADDLE_ENVIRONMENT = os.getenv("PADDLE_ENVIRONMENT", "sandbox")  # "sandbox" | "production"
PADDLE_API_KEY = os.getenv("PADDLE_API_KEY", "")
PADDLE_CLIENT_TOKEN = os.getenv("PADDLE_CLIENT_TOKEN", "")
PADDLE_WEBHOOK_SECRET = os.getenv("PADDLE_WEBHOOK_SECRET", "")
# Price IDs per tier — set in .env for each environment
PADDLE_PRICE_ID_STANDARD = os.getenv("PADDLE_PRICE_ID_STANDARD", "")
PADDLE_PRICE_ID_PRO = os.getenv("PADDLE_PRICE_ID_PRO", "")
PADDLE_PRICE_ID_ENTERPRISE = os.getenv("PADDLE_PRICE_ID_ENTERPRISE", "")

# =============================================================================
# WhatsApp Business Notifications (M002: pywa)
# =============================================================================
# Obtain from Meta Business Manager / WhatsApp Business Platform
# Dashboard: https://developers.facebook.com/apps → WhatsApp → API Setup
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_ACCESS_TOKEN = os.getenv("WHATSAPP_ACCESS_TOKEN", "")
# Set to True to use WhatsApp test numbers (no approved template required)
WHATSAPP_USE_SANDBOX = os.getenv("WHATSAPP_USE_SANDBOX", "False").lower() == "true"


# =============================================================================
# CORS Settings (Environment-driven)
# =============================================================================
#
# PRODUCTION: Set CORS_ORIGINS env var to your frontend domain(s)
#   Example: CORS_ORIGINS=https://app.cleanproof.com
#
# SECURITY: Wildcards (*) are NEVER allowed. Each origin must be explicit.
# =============================================================================

if DEBUG:
    # Development: Allow all origins for easier local development
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = []  # Not used when ALLOW_ALL is True
else:
    # Production: explicit origins from environment
    _cors_origins_env = os.getenv("CORS_ORIGINS", "")
    if _cors_origins_env:
        CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins_env.split(",") if o.strip()]
    else:
        raise ValueError(
            "CORS_ORIGINS environment variable is required in production mode. "
            "Example: CORS_ORIGINS=https://app.cleanproof.com,https://www.cleanproof.com"
        )
    CORS_ALLOW_ALL_ORIGINS = False
# =============================================================================
# Email (SMTP via Gmail)
# =============================================================================

# Recipient for system emails (demo requests, contact messages, job reports)
FOUNDER_DEMO_EMAIL = os.getenv("FOUNDER_DEMO_EMAIL", "photobp2019@gmail.com")

# M004/S02: Frontend URL for email verification links
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")

# =============================================================================
# Email Configuration (environment-driven)
# =============================================================================
# Supports: SMTP (Gmail, SendGrid, Mailgun, SES), or console (dev)
#
# For SendGrid SMTP:
#   EMAIL_HOST=smtp.sendgrid.net
#   EMAIL_PORT=587
#   EMAIL_HOST_USER=apikey
#   EMAIL_HOST_PASSWORD=SG.your-api-key
#
# For Mailgun SMTP:
#   EMAIL_HOST=smtp.mailgun.org
#   EMAIL_PORT=587
#   EMAIL_HOST_USER=postmaster@mg.yourdomain.com
#   EMAIL_HOST_PASSWORD=your-mailgun-password
#
# For AWS SES:
#   EMAIL_HOST=email-smtp.us-east-1.amazonaws.com
#   EMAIL_PORT=587
#   EMAIL_HOST_USER=your-ses-smtp-user
#   EMAIL_HOST_PASSWORD=your-ses-smtp-password
# =============================================================================

_email_password = os.environ.get("EMAIL_HOST_PASSWORD")
if _email_password or not DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    # Development: print emails to console if no password configured
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("true", "1", "yes")

# Sender credentials
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "reports.cleanproof@gmail.com")
EMAIL_HOST_PASSWORD = _email_password or ""

# Default "From" address
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "Proof Platform <noreply@proofplatform.com>"
)

# Server email for error reports
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)


# =============================================================================
# Logging Configuration
# =============================================================================
# Development: human-readable console output
# Production: structured JSON for log aggregation (grep-friendly, parseable)
# =============================================================================

_LOG_FORMAT = os.getenv("LOG_FORMAT", "json" if not DEBUG else "text")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
        "json": {
            "()": "apps.emails.__init__" if False else "logging.Formatter",  # placeholder — replaced below
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG" if DEBUG else "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple" if DEBUG else "verbose",
        },
        "console_json": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG" if DEBUG else "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING" if not DEBUG else "DEBUG",
            "propagate": False,
        },
        # Suppress noisy loggers in production
        "django.security.DisallowedHost": {
            "handlers": ["console"],
            "level": "CRITICAL",
            "propagate": False,
        },
        # App loggers — structured output
        "apps.emails": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "apps.api": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "apps.maintenance": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Production: Replace formatter with structured JSON
if _LOG_FORMAT == "json":
    LOGGING["formatters"]["json"] = {
        "()": "config.logging_json.JsonFormatter",
    }
    LOGGING["handlers"]["console"]["formatter"] = "json"
    LOGGING["handlers"]["console_json"]["formatter"] = "json"


# =============================================================================
# Security Headers (Production)
# =============================================================================

if not DEBUG:
    # HTTPS settings
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True").lower() in ("true", "1", "yes")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Other security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # CSRF trusted origins (required for Django 4.0+)
    _csrf_trusted = os.getenv("CSRF_TRUSTED_ORIGINS", "")
    if _csrf_trusted:
        CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted.split(",") if o.strip()]
    else:
        # Default to CORS origins if not explicitly set
        CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()


# =============================================================================
# Celery Configuration (Stage 14: Automated Visit Generation)
# =============================================================================

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")

# =============================================================================
# Cache Configuration (M006/S01: API Response Caching)
# =============================================================================
# Production: Redis cache (same instance as Celery, separate DB index)
# Test/dev: falls back to LocMemCache when CACHE_BACKEND is unset
_CACHE_BACKEND = os.getenv("CACHE_BACKEND", "")

if _CACHE_BACKEND == "redis" or os.getenv("REDIS_URL"):
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.getenv("REDIS_URL", "redis://localhost:6379/1"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "IGNORE_EXCEPTIONS": True,  # Degrade gracefully if Redis is down
                "SOCKET_CONNECT_TIMEOUT": 2,
                "SOCKET_TIMEOUT": 2,
            },
            "KEY_PREFIX": "proof_platform",
            "TIMEOUT": 300,  # 5 minutes default TTL
        }
    }
else:
    # Development / test: in-process memory cache (no Redis required)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "proof-platform-dev",
        }
    }

CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Dubai"  # Match Django TIME_ZONE
CELERY_ENABLE_UTC = True

# Use django-celery-beat for database-backed periodic tasks
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"


# =============================================================================
# Sentry Error Tracking (M002: Observability)
# =============================================================================

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.redis import RedisIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
import logging as _logging

SENTRY_DSN = os.getenv("SENTRY_DSN", "")
SENTRY_ENVIRONMENT = os.getenv("SENTRY_ENVIRONMENT", "development" if DEBUG else "production")
SENTRY_TRACES_SAMPLE_RATE = float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.2" if not DEBUG else "0.0"))
SENTRY_PROFILES_SAMPLE_RATE = float(os.getenv("SENTRY_PROFILES_SAMPLE_RATE", "0.1" if not DEBUG else "0.0"))

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=SENTRY_ENVIRONMENT,
        integrations=[
            DjangoIntegration(
                transaction_style="url",       # group by URL pattern, not function
                middleware_spans=True,
                signals_spans=False,           # too noisy
                cache_spans=False,
            ),
            CeleryIntegration(
                monitor_beat_tasks=True,       # track beat task health
                propagate_traces=True,         # link Celery traces to parent requests
            ),
            RedisIntegration(),
            LoggingIntegration(
                level=_logging.INFO,           # capture INFO+ as breadcrumbs
                event_level=_logging.ERROR,    # send ERROR+ as Sentry events
            ),
        ],
        traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
        profiles_sample_rate=SENTRY_PROFILES_SAMPLE_RATE,
        send_default_pii=False,                # GDPR — no request bodies or user IPs
        attach_stacktrace=True,                # include stacktrace on all events
        release=os.getenv("APP_VERSION", "unknown"),
    )
