# Generated by Django 5.2.9 on 2026-02-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_maintenance', '0006_part_visitpart'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='maintenancenotificationlog',
            new_name='apps_mainte_company_19c417_idx',
            old_name='maintenance_company_d0c8e3_idx',
        ),
    ]
