# Generated by Django 5.2.9 on 2026-02-16 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_locations', '0003_add_context_to_checklisttemplate'),
        ('apps_maintenance', '0007_rename_maintenance_company_d0c8e3_idx_apps_mainte_company_19c417_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='default_checklist_template',
            field=models.ForeignKey(blank=True, help_text='Default checklist applied when creating visits for assets of this type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types', to='apps_locations.checklisttemplate'),
        ),
    ]
