# Generated by Django 5.2.9 on 2026-02-16 13:36

import apps.maintenance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_maintenance', '0008_assettype_default_checklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Document name or title', max_length=200)),
                ('document_type', models.CharField(choices=[('manual', 'Manual'), ('warranty', 'Warranty Document'), ('certificate', 'Certificate'), ('inspection', 'Inspection Report'), ('photo', 'Photo'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(help_text='Uploaded file (PDF, image, etc.)', upload_to=apps.maintenance.models.asset_document_upload_path)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='apps_maintenance.asset')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_asset_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Document',
                'verbose_name_plural': 'Asset Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
