# Generated by Django 5.2.9 on 2026-02-16 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_maintenance', '0009_asset_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='reorder_point',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Alert threshold for low stock', max_digits=10),
        ),
        migrations.AddField(
            model_name='part',
            name='reorder_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suggested quantity to reorder', max_digits=10),
        ),
        migrations.AddField(
            model_name='part',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current stock quantity', max_digits=10),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('correction', 'Correction')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positive value for adjustment amount', max_digits=10)),
                ('quantity_before', models.DecimalField(decimal_places=2, help_text='Stock quantity before adjustment', max_digits=10)),
                ('quantity_after', models.DecimalField(decimal_places=2, help_text='Stock quantity after adjustment', max_digits=10)),
                ('reason', models.CharField(blank=True, help_text='Reason for adjustment', max_length=200)),
                ('reference', models.CharField(blank=True, help_text='Reference (e.g., PO number, visit ID)', max_length=100)),
                ('adjusted_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='apps_maintenance.part')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'ordering': ['-adjusted_at'],
            },
        ),
    ]
