# Generated by Django 5.2.9 on 2026-03-17 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0009_paddle_models'),
        ('apps_jobs', '0012_whatsapp_notification_log'),
        ('apps_maintenance', '0010_stock_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='servicecontract',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, help_text='Contract end date (null = open-ended)', null=True),
        ),
        migrations.AlterField(
            model_name='servicecontract',
            name='start_date',
            field=models.DateField(db_index=True, help_text='Contract start date'),
        ),
        migrations.AlterField(
            model_name='servicecontract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='WhatsAppNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('assignment', 'Assignment Alert'), ('completion', 'Completion Notification'), ('sla_warning', 'SLA Warning')], max_length=30)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('to_phone', models.CharField(max_length=30)),
                ('wa_message_id', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_notifications', to='apps_accounts.company')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_notifications', to='apps_jobs.job')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_whatsapp_notifications', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_whatsapp_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Notification Log',
                'verbose_name_plural': 'WhatsApp Notification Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'kind', 'created_at'], name='apps_mainte_company_a80380_idx')],
            },
        ),
    ]
