# Generated by Django 5.2 — M011/S02: Production DB indexes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_maintenance", "0011_whatsapp_notification_log"),
    ]

    operations = [
        # Asset: compound index for list queries filtered by company+location+active
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["company", "location", "is_active"],
                name="asset_co_loc_active_idx",
            ),
        ),
        # Asset: compound index for company + is_active (most common filter pattern)
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["company", "is_active"],
                name="asset_co_active_idx",
            ),
        ),
        # Part: compound index for low-stock queries
        migrations.AddIndex(
            model_name="part",
            index=models.Index(
                fields=["company", "is_active", "stock_quantity"],
                name="part_co_active_stock_idx",
            ),
        ),
        # RecurringVisitTemplate: compound index for scheduled generation
        migrations.AddIndex(
            model_name="recurringvisittemplate",
            index=models.Index(
                fields=["company", "is_active", "start_date"],
                name="rvt_co_active_start_idx",
            ),
        ),
        # VisitPart: compound index for visit parts lookup
        migrations.AddIndex(
            model_name="visitpart",
            index=models.Index(
                fields=["job", "part"],
                name="visitpart_job_part_idx",
            ),
        ),
        # ServiceContract: index for location-scoped queries
        migrations.AddIndex(
            model_name="servicecontract",
            index=models.Index(
                fields=["company", "status", "end_date"],
                name="contract_co_status_end_idx",
            ),
        ),
    ]
