# Generated by Django 5.2.9 on 2026-03-17 05:32

import apps.webhooks.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_accounts', '0009_paddle_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='HTTPS URL that will receive webhook POST requests.', max_length=500)),
                ('secret', models.CharField(default=apps.webhooks.models._generate_secret, help_text='HMAC-SHA256 secret for request signing (auto-generated). Never share this publicly.', max_length=128)),
                ('events', models.JSONField(default=list, help_text='List of event types to subscribe to, e.g. ["job.completed", "sla.violated"].')),
                ('is_active', models.BooleanField(default=True, help_text='Only active endpoints receive deliveries. Requires Enterprise plan tier.')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='apps_accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhook_endpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'verbose_name_plural': 'Webhook Endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('job.completed', 'Job Completed'), ('sla.violated', 'SLA Violated'), ('proof.missing', 'Proof Missing')], max_length=50)),
                ('payload', models.JSONField(help_text='Serialized payload that was sent (or attempted).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('http_status', models.IntegerField(blank=True, help_text='HTTP response status code from the receiving endpoint.', null=True)),
                ('response_body', models.TextField(blank=True, help_text='First 1000 chars of response body for debugging.')),
                ('error_message', models.TextField(blank=True, help_text='Exception message if delivery failed.')),
                ('duration_ms', models.IntegerField(blank=True, help_text='Request duration in milliseconds.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='apps_webhooks.webhookendpoint')),
            ],
            options={
                'verbose_name': 'Webhook Delivery Log',
                'verbose_name_plural': 'Webhook Delivery Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['company', 'is_active'], name='apps_webhoo_company_8d5373_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverylog',
            index=models.Index(fields=['endpoint', 'event', 'created_at'], name='apps_webhoo_endpoin_f32c66_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverylog',
            index=models.Index(fields=['status', 'created_at'], name='apps_webhoo_status_624549_idx'),
        ),
    ]
