# Generated by Django 5.2.9 on 2026-02-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0007_add_plan_tier'),
        ('apps_locations', '0003_add_context_to_checklisttemplate'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='users_role_valid',
        ),
        migrations.AddField(
            model_name='user',
            name='customer_locations',
            field=models.ManyToManyField(blank=True, help_text='Locations this customer can access (only for role=customer)', related_name='customer_users', to='apps_locations.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff'), ('cleaner', 'Cleaner'), ('customer', 'Customer')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'manager', 'staff', 'cleaner', 'customer'])), name='users_role_valid'),
        ),
    ]
