# Generated by Django 5.2.9 on 2026-03-16 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0008_customer_portal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaddleSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paddle_subscription_id', models.CharField(db_index=True, help_text='Paddle subscription ID (sub_xxx)', max_length=100, unique=True)),
                ('paddle_customer_id', models.CharField(blank=True, help_text='Paddle customer ID (ctm_xxx)', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past Due'), ('paused', 'Paused'), ('trialing', 'Trialing')], default='active', max_length=20)),
                ('plan_tier', models.CharField(blank=True, help_text='Pricing tier derived from Paddle price ID: standard/pro/enterprise', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('paddle_update_url', models.URLField(blank=True, help_text='URL for customer to update payment method')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paddle_subscription', to='apps_accounts.company')),
            ],
            options={
                'db_table': 'paddle_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PaddleWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='Paddle event ID (evt_xxx) — used for deduplication', max_length=100, unique=True)),
                ('event_type', models.CharField(help_text='Paddle event type (e.g. subscription.activated)', max_length=100)),
                ('payload', models.JSONField(help_text='Full raw Paddle webhook payload JSON')),
                ('occurred_at', models.DateTimeField(help_text='When the event occurred (from Paddle payload)')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When we received the webhook')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When we finished processing the event', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Exception text if status=failed')),
            ],
            options={
                'db_table': 'paddle_webhook_events',
                'indexes': [models.Index(fields=['event_type', 'status'], name='paddle_webh_event_t_e8d969_idx'), models.Index(fields=['occurred_at'], name='paddle_webh_occurre_4b42b6_idx')],
            },
        ),
    ]
