# Generated by Django 5.2.9 on 2026-03-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0013_add_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Demo account — read-only, no billing'),
        ),
    ]
