# Generated by Django 5.2.9 on 2026-02-18 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_jobs', '0010_add_priority_and_sla_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobphoto',
            name='last_replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobphoto',
            name='last_replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobphoto',
            name='original_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobphoto',
            name='replacement_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobphoto',
            name='replacement_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
