# Generated by Django 5.2.9 on 2026-03-17 03:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0009_paddle_models'),
        ('apps_jobs', '0011_jobphoto_last_replaced_at_jobphoto_last_replaced_by_and_more'),
        ('apps_locations', '0003_add_context_to_checklisttemplate'),
        ('apps_maintenance', '0010_stock_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='scheduled_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('completed_unverified', 'Completed (Unverified)'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=30),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'status', 'actual_end_time'], name='jobs_co_status_endtime_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'context', 'status'], name='jobs_co_ctx_status_idx'),
        ),
    ]
