# Generated by Django 5.2.9 on 2026-03-17 06:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0011_add_branch_model'),
        ('apps_jobs', '0012_whatsapp_notification_log'),
        ('apps_locations', '0004_add_branch_fk_to_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringJobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='WEEKLY: 0=Mon, 6=Sun', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='MONTHLY: 1-28', null=True)),
                ('scheduled_start_time', models.TimeField(blank=True, null=True)),
                ('scheduled_end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_generated_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_job_templates', to='apps_locations.checklisttemplate')),
                ('cleaner', models.ForeignKey(blank=True, limit_choices_to={'role': 'cleaner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_job_templates', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_job_templates', to='apps_accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_job_templates', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_job_templates', to='apps_locations.location')),
            ],
            options={
                'db_table': 'recurring_job_templates',
                'ordering': ['name'],
            },
        ),
    ]
