# Generated by Django 5.2.9 on 2026-03-17 06:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0011_add_branch_model'),
        ('apps_jobs', '0013_add_recurring_job_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('gps_radius_m', models.PositiveIntegerField(default=100, help_text='Allowed distance from location for check-in/check-out (metres)')),
                ('check_in_window_minutes', models.PositiveIntegerField(default=30, help_text='Minutes before scheduled start that check-in is allowed')),
                ('check_out_window_minutes', models.PositiveIntegerField(default=30, help_text='Minutes after scheduled end before SLA is considered breached')),
                ('required_proof_photo', models.BooleanField(default=True, help_text='At least one photo required for job completion')),
                ('required_proof_checklist', models.BooleanField(default=False, help_text='All checklist items must be completed')),
                ('required_proof_signature', models.BooleanField(default=False, help_text='Customer signature required')),
                ('is_default', models.BooleanField(default=False, help_text='Use this policy when no location-specific policy is set')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='apps_accounts.company')),
            ],
            options={
                'db_table': 'sla_policies',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='sla_policy_override',
            field=models.ForeignKey(blank=True, help_text='Override SLA policy for this specific job. Falls back to location → company default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_overrides', to='apps_jobs.slapolicy'),
        ),
    ]
