# backend/apps/api/bilingual_pdf.py
"""
Bilingual Arabic/English Maintenance Visit PDF Report (M004/S01)

Generates a standalone PDF using fpdf2 (NOT ReportLab) with:
- Arabic and English labels side-by-side
- Correct RTL Arabic text via arabic_reshaper + bidi algorithm
- Bundled Amiri font for Arabic glyphs
- Falls back to English-only if Arabic font is unavailable

Architecture:
- generate_bilingual_visit_report_pdf(job): main entry point → bytes
- _reshape_arabic(text): arabic_reshaper + bidi → display-ready string
- _find_arabic_font(): locates bundled Amiri .ttf for fpdf2
- BilingualVisitReport(FPDF): page layout, header, sections

Usage:
    from apps.api.bilingual_pdf import generate_bilingual_visit_report_pdf
    pdf_bytes = generate_bilingual_visit_report_pdf(job)

Dependencies:
    fpdf2==2.8.3
    arabic-reshaper==3.0.0
    python-bidi==0.4.2
    Amiri-Regular.ttf  (bundled in apps/api/fonts/)
"""

import logging
import os
from typing import Optional

logger = logging.getLogger(__name__)

# Path to bundled Amiri font directory
_FONTS_DIR = os.path.join(os.path.dirname(__file__), "fonts")


def _find_arabic_font() -> Optional[str]:
    """
    Find Amiri-Regular.ttf in bundled fonts dir.
    Returns absolute path or None if not found.
    """
    candidates = [
        os.path.join(_FONTS_DIR, "Amiri-Regular.ttf"),
        os.path.join(_FONTS_DIR, "Amiri-Bold.ttf"),
    ]
    for path in candidates:
        if os.path.exists(path):
            return path
    logger.warning("Arabic font not found in %s — bilingual PDF will use English only", _FONTS_DIR)
    return None


def _reshape_arabic(text: str) -> str:
    """
    Apply arabic_reshaper + python-bidi to produce display-ready Arabic string.
    Required for correct glyph joining and RTL visual order in PDFs.
    Returns the original text unchanged on any error.
    """
    if not text:
        return text
    try:
        import arabic_reshaper
        from bidi.algorithm import get_display
        reshaped = arabic_reshaper.reshape(text)
        return get_display(reshaped)
    except Exception as exc:
        logger.warning("Arabic reshaping failed: %s", exc)
        return text


# =============================================================================
# Bilingual label pairs  (Arabic, English)
# =============================================================================

LABELS = {
    "report_title_ar":    "تقرير زيارة الصيانة",
    "report_title_en":    "Maintenance Visit Report",
    "company_ar":         "الشركة",
    "company_en":         "Company",
    "visit_id_ar":        "رقم الزيارة",
    "visit_id_en":        "Visit ID",
    "location_ar":        "الموقع",
    "location_en":        "Location",
    "asset_ar":           "المعدة",
    "asset_en":           "Asset",
    "asset_type_ar":      "نوع المعدة",
    "asset_type_en":      "Asset Type",
    "technician_ar":      "الفني",
    "technician_en":      "Technician",
    "category_ar":        "الفئة",
    "category_en":        "Category",
    "scheduled_date_ar":  "التاريخ المجدول",
    "scheduled_date_en":  "Scheduled Date",
    "completed_at_ar":    "تاريخ الإنجاز",
    "completed_at_en":    "Completed At",
    "status_ar":          "الحالة",
    "status_en":          "Status",
    "completed_status_ar": "مكتمل",
    "completed_status_en": "Completed",
    "sla_ar":             "معيار مستوى الخدمة",
    "sla_en":             "SLA",
    "on_time_ar":         "في الوقت المحدد",
    "on_time_en":         "On Time",
    "overdue_ar":         "متأخر",
    "overdue_en":         "Overdue",
    "notes_ar":           "ملاحظات",
    "notes_en":           "Notes",
    "checklist_ar":       "قائمة المراجعة",
    "checklist_en":       "Checklist",
    "completed_item_ar":  "✓",
    "pending_item_ar":    "○",
    "photos_ar":          "الصور",
    "photos_en":          "Photos",
    "before_ar":          "قبل",
    "before_en":          "Before",
    "after_ar":           "بعد",
    "after_en":           "After",
    "not_provided_ar":    "غير متوفر",
    "not_provided_en":    "Not provided",
    "generated_by_ar":    "تم الإنشاء بواسطة",
    "generated_by_en":    "Generated by",
    "platform_name":      "MaintainProof",
}

# Status display mapping
STATUS_AR = {
    "completed": "مكتمل",
    "in_progress": "قيد التنفيذ",
    "scheduled": "مجدول",
    "cancelled": "ملغي",
}


def generate_bilingual_visit_report_pdf(job) -> bytes:
    """
    Generate a bilingual Arabic/English PDF for a maintenance service visit.

    Args:
        job: Job instance (maintenance context, completed status)

    Returns:
        PDF bytes

    The PDF uses fpdf2 (not ReportLab) with Amiri Arabic font.
    Falls back to English-only if font unavailable.
    """
    from fpdf import FPDF

    arabic_font_path = _find_arabic_font()
    has_arabic = arabic_font_path is not None

    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Load fonts
    # fpdf2 ships with DejaVu which covers Latin + many scripts
    if has_arabic:
        try:
            pdf.add_font("Amiri", style="", fname=arabic_font_path)
            pdf.add_font("Amiri", style="B", fname=arabic_font_path)
        except Exception as exc:
            logger.warning("Failed to load Amiri font: %s — falling back to English only", exc)
            has_arabic = False

    # After loading fonts, set Amiri as default (it covers both Arabic and Latin)
    if has_arabic:
        pdf.set_font("Amiri", size=10)
    else:
        pdf.set_font("Helvetica", size=10)

    def write_bilingual_row(label_ar: str, label_en: str, value_ar: str, value_en: str, bold_value=False):
        """Write a two-column bilingual row: [EN label: EN value | AR label: AR value]."""
        col_w = 90
        row_h = 7

        # English side (left) — use Amiri when loaded (supports full Unicode including em-dash)
        en_font = "Amiri" if has_arabic else "Helvetica"
        pdf.set_font(en_font, style="B", size=9)
        pdf.cell(40, row_h, label_en + ":", border=0, align="L")
        pdf.set_font(en_font, style="B" if bold_value else "", size=9)
        pdf.cell(col_w - 40, row_h, str(value_en), border=0, align="L")

        # Arabic side (right) — RTL
        if has_arabic:
            ar_label = _reshape_arabic(label_ar)
            ar_value = _reshape_arabic(str(value_ar))
            pdf.set_font("Amiri", style="B", size=10)
            pdf.cell(col_w - 40, row_h, ar_value, border=0, align="R")
            pdf.set_font("Amiri", style="", size=10)
            pdf.cell(40, row_h, ar_label + " :", border=0, align="R")

        pdf.ln(row_h)

    def section_header(title_en: str, title_ar: str = ""):
        pdf.ln(3)
        pdf.set_fill_color(45, 45, 55)
        pdf.set_text_color(255, 255, 255)
        en_font = "Amiri" if has_arabic else "Helvetica"
        pdf.set_font(en_font, style="B", size=10)
        header_text = title_en
        if has_arabic and title_ar:
            ar_title = _reshape_arabic(title_ar)
            pdf.set_font("Amiri", style="B", size=11)
            header_text = f"{title_en}  |  {ar_title}"
        pdf.cell(0, 8, header_text, fill=True, new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(2)

    # ─── Header ──────────────────────────────────────────────────────────────
    pdf.set_fill_color(18, 18, 24)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", style="B", size=14)

    title_en = LABELS["report_title_en"]
    title_ar = _reshape_arabic(LABELS["report_title_ar"]) if has_arabic else ""
    header_title = f"{title_en}  |  {title_ar}" if has_arabic else title_en
    en_font = "Amiri" if has_arabic else "Helvetica"
    pdf.set_font(en_font, style="B", size=14)
    pdf.cell(0, 12, header_title, fill=True, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # ─── Visit Details ────────────────────────────────────────────────────────
    section_header(LABELS["visit_id_en"], LABELS["visit_id_ar"])

    company_name = job.company.name if job.company else "-"
    location_name = job.location.name if job.location else "-"
    asset_name = job.asset.name if job.asset else "-"
    asset_type_name = job.asset.asset_type.name if job.asset and job.asset.asset_type else "-"
    tech_name = job.cleaner.full_name if job.cleaner else "-"
    category_name = job.maintenance_category.name if job.maintenance_category else "-"
    scheduled = job.scheduled_date.strftime("%d %b %Y") if job.scheduled_date else "-"
    completed_at = (
        job.actual_end_time.strftime("%d %b %Y %H:%M") if job.actual_end_time else "-"
    )
    sla_status = "On Time" if not getattr(job, "sla_violated", False) else "Overdue"
    sla_ar = LABELS["on_time_ar"] if sla_status == "On Time" else LABELS["overdue_ar"]

    pdf.set_font("Helvetica", size=9)
    write_bilingual_row(LABELS["visit_id_ar"], LABELS["visit_id_en"], f"#{job.id}", f"#{job.id}", bold_value=True)
    write_bilingual_row(LABELS["company_ar"], LABELS["company_en"], company_name, company_name)
    write_bilingual_row(LABELS["location_ar"], LABELS["location_en"], location_name, location_name)
    write_bilingual_row(LABELS["asset_ar"], LABELS["asset_en"], asset_name, asset_name)
    write_bilingual_row(LABELS["asset_type_ar"], LABELS["asset_type_en"], asset_type_name, asset_type_name)
    write_bilingual_row(LABELS["technician_ar"], LABELS["technician_en"], tech_name, tech_name)
    write_bilingual_row(LABELS["category_ar"], LABELS["category_en"], category_name, category_name)
    write_bilingual_row(LABELS["scheduled_date_ar"], LABELS["scheduled_date_en"], scheduled, scheduled)
    write_bilingual_row(LABELS["completed_at_ar"], LABELS["completed_at_en"], completed_at, completed_at)
    write_bilingual_row(
        LABELS["status_ar"], LABELS["status_en"],
        STATUS_AR.get(job.status, job.status),
        LABELS["completed_status_en"],
        bold_value=True,
    )
    write_bilingual_row(LABELS["sla_ar"], LABELS["sla_en"], sla_ar, sla_status)

    # ─── Notes ───────────────────────────────────────────────────────────────
    if job.manager_notes:
        section_header(LABELS["notes_en"], LABELS["notes_ar"])
        en_font = "Amiri" if has_arabic else "Helvetica"
        pdf.set_font(en_font, size=9)
        pdf.multi_cell(0, 6, job.manager_notes)
        pdf.ln(2)

    # ─── Checklist ────────────────────────────────────────────────────────────
    checklist_items = list(job.checklist_items.all()) if hasattr(job, "checklist_items") else []
    if checklist_items:
        section_header(LABELS["checklist_en"], LABELS["checklist_ar"])
        en_font = "Amiri" if has_arabic else "Helvetica"
        pdf.set_font(en_font, size=9)
        for item in checklist_items:
            mark = "v" if item.is_completed else "o"
            text = f"  {mark}  {item.text}"
            pdf.cell(0, 6, text, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    # ─── Photos ───────────────────────────────────────────────────────────────
    photos = list(job.photos.select_related("file").all()) if hasattr(job, "photos") else []
    by_type = {p.photo_type: p for p in photos}

    before = by_type.get("before")
    after = by_type.get("after")

    if before or after:
        section_header(LABELS["photos_en"], LABELS["photos_ar"])
        _add_photo_row(pdf, before, LABELS["before_en"], LABELS["before_ar"], after, LABELS["after_en"], LABELS["after_ar"], has_arabic)

    # ─── Footer ───────────────────────────────────────────────────────────────
    pdf.ln(6)
    en_font = "Amiri" if has_arabic else "Helvetica"
    pdf.set_font(en_font, size=7)
    pdf.set_text_color(120, 120, 120)
    from django.utils import timezone as tz
    now_str = tz.now().strftime("%Y-%m-%d %H:%M UTC")
    footer_en = f"{LABELS['generated_by_en']} {LABELS['platform_name']}  -  {now_str}"
    pdf.cell(0, 5, footer_en, align="C", new_x="LMARGIN", new_y="NEXT")
    if has_arabic:
        footer_ar = _reshape_arabic(f"{LABELS['platform_name']} - {LABELS['generated_by_ar']}")
        pdf.set_font("Amiri", size=9)
        pdf.cell(0, 5, footer_ar, align="C", new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())


def _add_photo_row(pdf, before, before_label_en, before_label_ar, after, after_label_en, after_label_ar, has_arabic):
    """Add before/after photo pair to the PDF (embedded images)."""
    col_w = 85
    img_h = 55

    labels = []
    paths = []

    for photo, label_en, label_ar in [(before, before_label_en, before_label_ar), (after, after_label_en, after_label_ar)]:
        label = f"{label_en}" + (f" | {_reshape_arabic(label_ar)}" if has_arabic else "")
        labels.append(label)

        path = None
        if photo and photo.file and photo.file.file_url:
            from apps.api.pdf import _resolve_media_path
            abs_path = _resolve_media_path(photo.file.file_url)
            if abs_path and os.path.exists(abs_path):
                path = abs_path
        paths.append(path)

    x_start = pdf.get_x()
    y_start = pdf.get_y()

    for i, (label, path) in enumerate(zip(labels, paths)):
        x = x_start + i * (col_w + 5)
        pdf.set_font("Helvetica", style="B", size=8)
        pdf.set_xy(x, y_start)
        pdf.cell(col_w, 6, label, ln=False)
        pdf.set_xy(x, y_start + 7)
        if path:
            try:
                pdf.image(path, x=x, y=y_start + 7, w=col_w, h=img_h)
            except Exception:
                pdf.set_font("Helvetica", size=8)
                pdf.set_xy(x, y_start + 7)
                pdf.cell(col_w, 6, "Image unavailable")
        else:
            pdf.set_font("Helvetica", size=8)
            pdf.set_xy(x, y_start + 7)
            pdf.cell(col_w, 6, LABELS["not_provided_en"])

    pdf.set_y(y_start + img_h + 10)
