# Generated by Django 5.2.9 on 2026-03-17 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0011_add_branch_model'),
        ('apps_locations', '0003_add_context_to_checklisttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='apps_accounts.branch'),
        ),
    ]
