# Generated by Django 5.2.9 on 2026-03-17 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_jobs', '0014_add_sla_policy'),
        ('apps_locations', '0004_add_branch_fk_to_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='apps_jobs.slapolicy'),
        ),
    ]
